version: 2.1

# Define pipeline parameters
parameters:
  is_pull_request:
    type: boolean
    default: false

# Define jobs
jobs:
  staging:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  promote-production-preview:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Promoting to preview"
          command: "echo Promoting to Production Preview"

# Define workflows
workflows:
  # Use a dynamic workflow with parameters
  version: 2
  preview-staging:
    when: << pipeline.parameters.is_pull_request >>
    jobs:
      - staging:
          filters:
            branches:
              only: main
      - promote-production-preview:
          requires:
            - staging
          filters:
            branches:
              only: main
